######################## Spring Profile 切换环境 ########################
## 切换日志环境、数据源等配置
#  默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my -spring-boot.jar --spring.profiles.active=prod
#  注意 "---" 表示：一组配置
# 开发环境配置
spring:
# profiles: dev
#自动重启默认开发时开启
 devtools:
  restart:
   enabled: true
 thymeleaf:
   cache: false
  #redis配置
 redis:
  host: 14.29.79.226
  port: 6379
  password: gt@123456
 session:
  store-type: redis


datasource:
 druid:
  url: jdbc:mysql://14.29.79.226:3306/gt_aliyuan?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
  username: root
  password: gt123456
  driver-class-name: com.mysql.jdbc.Driver
  platform: mysql
  type: com.alibaba.druid.pool.DruidDataSource
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,wall,slf4j
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  #useGlobalDataSourceStat: true

server:
  port: 8080
  session:
    timeout: 30





