######################## Spring Profile 切换环境 ########################
## 切换日志环境、数据源等配置
#  默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my -spring-boot.jar --spring.profiles.active=prod
#  注意 "---" 表示：一组配置
# 开发环境配置
spring:
# profiles: dev
#自动重启默认开发时开启
 devtools:
  restart:
   enabled: true
 thymeleaf:
   cache: false
  #redis配置
 redis:
  host: 10.10.242.2
  port: 6379
  password: gt@123456
  database: 4

 session:
  store-type: redis


datasource:
 druid:
   url: jdbc:mysql://183.47.242.2:3306/gt?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
   username: root
   password: gt26609632
   driver-class-name: com.mysql.jdbc.Driver
   platform: mysql
   type: com.alibaba.druid.pool.DruidDataSource
   # 下面为连接池的补充设置，应用到上面所有数据源中
   # 初始化大小，最小，最大
   initialSize: 5
   maxActive: 20
   # 配置获取连接等待超时的时间
   maxWait: 60000
   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 五分钟
   timeBetweenEvictionRunsMillis: 300000
   # 配置一个连接在池中最小生存的时间，单位是毫秒
   minEvictableIdleTimeMillis: 30000
   validationQuery: select 1
   testWhileIdle: true
   testOnBorrow: true
   testOnReturn: true
   # 打开PSCache，并且指定每个连接上PSCache的大小
   # poolPreparedStatements: true
   # maxPoolPreparedStatementPerConnectionSize: 20
   # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
   filters: stat,wall,slf4j
   # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
   # 合并多个DruidDataSource的监控数据
   #useGlobalDataSourceStat: true
   #useGlobalDataSourceStat: true
#   stat-view-servlet:
#    #IP白(allow)/黑(deny)名单 (存在共同时，deny优先于allow) : 如果满足deny的话提示:Sorry, you are not permitted to view this page.
#    allow: 127.0.0.1,192.168.3.47
#    login-username: admin
#    login-password: admin
#    reset-enable: false
#    url-pattern: /druid/*
#    # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
#    # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
#    # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#   aop-patterns: com.gt.*.dao.*,com.gt.mall.*.service.*

######################## 开发环境配置 ########################

server:
  port: 8080
  session:
    timeout: 30

web:
 webHome: http://member.duofriend.com/
 wxmp_home: http://duofriend.com/
 wxmpsignKey: WXMP2017
 cardNoKey: 4204D69FDC8932B631653F5D3E0EB6A6
 sms_name: 多粉平台
 socket_url: http://183.47.242.2:8881
 redis_ip: 10.10.242.2
 redis_port: 6379
 redis_password: gt@123456
 redis_database: 0
 res_image_path: /home/server/project/staticSource/upload  #图片存放路径
 #图片资源ftp ip
 static_source_ftp_ip: 10.10.242.3
 #图片资源ftp端口
 static_source_ftp_port: 21
 #图片资源ftp用户名
 static_source_ftp_user: gt123456
 #图片资源ftp密码
 static_source_ftp_password: gt123456

  #联盟卡
  untion_url:

  #多粉 11510 微站 14202
  sms_tmplId: 11510


redisSession:
 domainName: .duofriend.com
 cookiePath: /
 cookieName: WXMPJSESSIONID
